### PR TITLE
Some tweaks in the filename parser and a script

### PR DESCRIPTION
**Pull request by fcanc**
Hi, I'm pulling two different commits, sorry if they're not related but I can't figure out how to make two separate pull requests.
BTW, the descriptions for each commit are self-explanatory. Hope to further improve the filename parser in the near future.

### CODE REVIEW

**Comment by davide-romanini** [comment]
Is it normal that the commit list "grows"? I think the PR relates only to the first two commits (5574, a628).

**Comment by davide-romanini** [comment]
Merged all the 7 commits. Didn't test it a lot though.

**Comment by davide-romanini** [comment]
I'm merging the big comicapi extraction refactoring in comicstream-integr. If you plan other automatic code style enhancements wait a bit until I've aligned master since the diff and merge tool do not work in this situation..

**Comment by fcanc** [comment]
I didn't realize github added my other commits, they were meant to stay in my fork. 
I already made some changes a few days ago but didn't commit to github yet, what happens if I sync now?
I'm in the middle of reviewing some comments/docstrings and a few text strings in the GUI and CLI, not a big loss but I want to avoid messing with your commits...

**Comment by davide-romanini** [comment]
I suggest to try a merge in a new branch because I've factored out the classes in common with comicstreamer in a new repository (comicapi). For backward compatibiliy I left the original files (eg. comicarchive.py) that just import from the new package, but this will mess up diff and merge tools.

**Pull request merged**
